### ISSUE TITLE
Width of input too small for any tag greater than about 6 characters

### ISSUE THREAD

**Issue by seanahrens** [TimSchlechter/bootstrap-tagsinput#226]
When I type a tag on the demo site (http://timschlechter.github.io/bootstrap-tagsinput/examples/) the text types only for about 6 characters, before the underlying text input becomes clear and the text begins scrolling horizontally as I type:

![screen shot 2014-09-23 at 5 26 39 pm](https://cloud.githubusercontent.com/assets/109729/4370004/c9478d58-4303-11e4-8e0b-5fa1a41d860a.png)

(Browser: Chrome 37)

@kafeltz @vcastrejont is this the same issue you were discussing in #219?

**Comment by fbardel** [comment]
In bootstrap-tagsinput.js replace
`var inputWidth = (this.inputSize < 3 ? 3 : this.inputSize) + "em";`
By
`var inputWidth = "auto";`
