### ISSUE TITLE
Doesn't work with .input-group

### ISSUE THREAD

**Issue by schnauss** [TimSchlechter/bootstrap-tagsinput#288]
I'd like to be able to use .input-group-addon and .input-group-btn, but this plugin completely breaks input groups.

jsfiddle here: http://jsfiddle.net/cp5Lvtdo/

**Comment by lucknerjb** [comment]
We might consider supporting input-groups "natively" in the next major version release but for the time being, you'll need to handle the CSS changes on your own. I checked out the jsfiddle that you included and it seems as though the changes would be relatively simple.
