### ISSUE TITLE
Custom typeahead options doesn't work

### ISSUE THREAD

**Issue by fanmusic** [TimSchlechter/bootstrap-tagsinput#297]
Hi,

I'm using bootstrap-tagsinput with Typeahead Bootstrap version 2.3.2. It worked really well until I wanted to use custom matcher function for typeahead.

I look through your code in bootstrap-tagsinput.js, I think this line: self.$input.typeahead($.extend({}, options.typeahead, {default typeahead options}) is not correct. Because the default typeahead options put on the right will overwrite all of my custom options.

Could you help to take a look? Because I don't want to change your code to do my work.

Thanks,
Huy.

**Comment by Cabu** [comment]
I have a similar problem. I added to Bloodhound a new tokenizer to be able to search anywhere in a word and not simply at the beginning. But whatever I do, tagsinput revert to the basic whitespace tokenizer... I have used word for words the Typeahead example with just a change to the datumTokenizer who read: "datumTokenizer: Bloodhound.tokenizers.obj.allchars('name'),"

**Comment by lucknerjb** [comment]
See #305. Better support for typeahead is coming.
