### ISSUE TITLE
Use without Bootstrap?

### ISSUE THREAD

**Issue by BenRacicot** [TimSchlechter/bootstrap-tagsinput#300]
Hey guys, any chance this could be used without Bootstrap?

**Comment by lucknerjb** [comment]
I don't think there is enough of a need for this feature to make it a global change but if you want to, you can omit including the bootstrap JS / CSS and the plugin will still work. Make sure you either copy over the bootstrap label CSS to your CSS file or style the labels yourself from scratch.

Hope that helps!
