### ISSUE TITLE
how to limit tags?

### ISSUE THREAD

**Issue by dincio** [timschlechter/bootstrap-tagsinput#325]
i tried this
  $("input").tagsinput({
        limit: 3
    });

and this
  $("#tag").tagsinput({
        maxTags: 3
    });

nothing work

**Comment by k-nut** [comment]
`maxTags` should work. See this fiddle: http://jsfiddle.net/fL3141uu/
If it is not working for you which browser and version are you using?

**Comment by FoxDanger** [comment]
Using Chrome here. In the link of the Fiddle it works. On my project didn't. Really don't know what is happening :(

same for maxChars

**Comment by lucknerjb** [comment]
Closing this for now as there does not seem to be an actual issue. If you can create a jsfiddle with your own code that shows the problem, please re-comment on this issue and we'll re-open it.
