### ISSUE TITLE
update bower to 0.5

### ISSUE THREAD

**Issue by solilin** [timschlechter/bootstrap-tagsinput#338]
Hello! Thanks for your library. Bootstrap-tagsinput version is still 0.4.2 in Bower. Could you update it please.

**Comment by szelga** [comment]
+1

**Comment by milotoor** [comment]
+2

**Comment by jinceon** [comment]
+3

**Comment by timschlechter** [comment]
Hi! Sorry, I'm not sure what has to be done for this. Can you guys tell me what/where to do?

**Comment by milotoor** [comment]
I'm not very familiar with Bower either. I use NPM for managing packages, and would appreciate it if 0.5.0 could be published. Is that possible?

**Comment by lucknerjb** [comment]
This has been done. Bower only checks proper semver versions so 0.5 is not valid. Pushed a new tag as 0.5.0

**Comment by milotoor** [comment]
Ok, but NPM only has version 0.4.2. Should I open a new issue for this...?

**Comment by milotoor** [comment]
see #330

**Comment by lucknerjb** [comment]
@milotoor Keep an eye out on #357 for updates on the NPM issue

**Comment by lucknerjb** [comment]
Hey all, check out #357 for an update on the npm issue. We should be good to go tonight once I re-publish it. I'll update that ticket at that time.
