### ISSUE TITLE
typeahead not working

### ISSUE THREAD

**Issue by martrix78** [timschlechter/bootstrap-tagsinput#370]
i am try run example
$('#input').tagsinput({
  typeahead: {
    source: ['Amsterdam', 'Washington', 'Sydney', 'Beijing', 'Cairo']
  },
  freeInput: true
});
 but typeahead not working :(

bootstrap v3.3.5 and  i use https://github.com/twitter/typeahead.js
What am i doing wrong?

**Comment by thejae** [comment]
The `typeahead.js` file has to be loaded before tagsinput and your script.

**Comment by lucknerjb** [comment]
@martrix78 Let me know if you're still having problems getting the plugin working. I'll close the issue for the time being.
