### ISSUE TITLE
Tagsinput not working

### ISSUE THREAD

**Issue by sanaalauddin** [timschlechter/bootstrap-tagsinput#395]
Hi. Im trying to use tagsinput, I added the input code and included the js and css file in my codeigniter view. But its not working. Which JS/Jquery files need to be included for it to work? 
I get the following errors in the console:

"NetworkError: 403 Forbidden" in both bootstrap-tagsinput.js/css

**Comment by scottwarren** [comment]
I'm not the owner of this repo, but can you put this into a [JSfiddle](jsfiddle.net) with your problem so we can help debug?


Is your page layout like this?:

```
<html>
<head>
<!-- Load your Bootstrap-tagsinput CSS here -->
</head>
<body>
<input data-role="tagsinput">
<!-- Load your Bootstrap-tagsinput Javascript here -->
</body>
```

**Comment by sanaalauddin** [comment]
Yes it is the same layout. I have tidied up my code a little but (its a long page using Codeigniter with multiple partial views). Heres the JSFiddle:

http://jsfiddle.net/a3jnv2he/

I really appreciate your help.
Thanks.

**Comment by scottwarren** [comment]
Can you create a smaller more focused JSfiddle with minimal amount of code that reproduces your issue?

**Comment by scottwarren** [comment]
Also:- the JSfiddle you have linked doesn't load the Bootstrap tagsinput as it still has some PHP code in there: `<script src="<?php echo base_url(); ?>public/tagsinput/bootstrap-tagsinput.min.js"></script>`

**Comment by sanaalauddin** [comment]
I updated the fiddle.

**Comment by scottwarren** [comment]
The original fiddle seems the same, do you have another (updated) Fiddle URL?

**Comment by scottwarren** [comment]
I forked the JSFiddle and included the CSS and JS for this library and it works: http://jsfiddle.net/ecg2dkq4/

**Comment by scottwarren** [comment]
This leads me to believe the Bootstrap Tags input CSS and/or Javascript is not being loaded (maybe it is 404ing). Check in your developer toolbar to make sure they're loading

**Comment by sanaalauddin** [comment]
I checked the jsfiddle link you gave.It isnt working for me.

**Comment by sanaalauddin** [comment]
Yay! Its working. Thanks alot. :)

**Comment by scottwarren** [comment]
no worries
